### ISSUE TITLE
plot: implement more default templates

### ISSUE THREAD

**Issue by pared** [iterative/dvc-render#20]
There are some plots that need to be implemented:
- [x] default
- [x] scatter
- [x] confusion matrix
- [ ] iterative/dvc-render#11
- [ ] feature importance
- [x] iterative/dvc-render#8

**Comment by daavoo** [comment]
Closing this one. Only 2 are left:

- https://github.com/iterative/dvc-render/issues/11 
we can track it in the issue.
- feature importance 
to some extent, this is a bar plot and there is the alternative to log the feature importance plot as image, so let's wait for a more specific request
