### ISSUE TITLE
Fill anchors instead of quoted anchors

### ISSUE THREAD

**Issue by WilliamHarvey97** [iterative/dvc-render#28]
In my custom vega-lite template, I tried do to something like this to compute the sum of squared residuals:
```
           "transform": [
                {
                    "joinaggregate": [
                        {
                            "op": "mean",
                            "field": "lab",
                            "as": "mean_y"
                        }
                    ]
                },
                {
                    "calculate": "pow(datum.<DVC_METRIC_Y> - datum.<DVC_METRIC_X>,2)",
                    "as": "SR"
                },
                {
                    "joinaggregate": [
                        {
                            "op": "sum",
                            "field": "SR",
                            "as": "SSR"
                        }
                    ]
                }
            ]
```

However, it seems impossible to do this because it looks like dvc-render replace only a quoted anchor like `f'"{cls.anchor(name)}"'`   instead of just the anchor `f'{cls.anchor(name)}'`

https://github.com/iterative/dvc-render/blob/422bfe61e1d1684a7d9a36c4d42f7c4ee6caf89f/src/dvc_render/vega_templates.py#L78

I didn't dig a lot into this, but I was just wondering if this could just be this way so we could use anchors on datum?

Thank you!

**Comment by pared** [comment]
The use case makes perfect sense. However, there is a certain reason why we quote the anchors, and this is because we treat the templates as dictionaries (not only in code, but for example in integrations, like vscode). Having quoted anchors allows us to parse and dump from/to json. We could think about involving some logic regarding the quotes. In the case provided by @WilliamHarvey97 we could detect that anchors are used within a string and it's safe to replace them without quotes.

**Comment by dberenbaum** [comment]
@pared Maybe we aren't being clear about whether templates are:

1. JSON documents where anchors are JSON values to be replaced OR
2. Text documents where anchors are strings to be replaced.

Is VS Code expecting each anchor to be injected as a value to a JSON key or as a string into a text doc? cc @mattseddon

**Comment by mattseddon** [comment]
@dberenbaum we are currently holding the template as a string so that we can do a `String.replace` and coerce the string into `JSON` like this:

```
  JSON.parse(
    template.replace('"<DVC_METRIC_DATA>"', JSON.stringify(datapoints))
  ) as TopLevelSpec
```

@pared we update the `colors` by overwriting that part of the encoding with:

```
  encoding: {
    color: {
      legend: { disable: true },
      scale: colorScale
    }
  }
```

Where `colorScale` has this type: `{ domain: string[]; range: string[] }`.

I am open to this changing we just need to be careful not to break anything.

Note: the way that our code is currently setup could be improved as we actually convert the initial CLI output into a JSON object and then back to a string, and then back to JSON once we know which datapoints we want to display.

**Comment by pared** [comment]
So I guess we have two ways to go:
1. Stop treating the templates as json dictionaries - that would require synchronous changes for DVC, Studio and VSCode, makes debugging a bit harder
2. Add functionality to fill anchors that are not entrenched within quotes, it would require a bit of logic inside template but should be possible to do. 
3. There still exists possibility to treat templates only as dictionaries. In this way, we would remove anchors and would need to provide `path` within dict and data to fill it with. Mentioning it only for historical accuracy, as it would require users to learn vega to create their own templates.

**Comment by daavoo** [comment]
Related https://github.com/iterative/dvc-render/issues/23 ?

**Comment by dberenbaum** [comment]
> There still exists possibility to treat templates only as dictionaries. In this way, we would remove anchors and would need to provide `path` within dict and data to fill it with. Mentioning it only for historical accuracy, as it would require users to learn vega to create their own templates.

@pared Could you explain more or show an example of what templates would look like without anchors?

Also, it might be fine to not allow use cases like `pow(datum.<DVC_METRIC_Y> - datum.<DVC_METRIC_X>,2)` as long as we clearly document it. We may need to update the docs anyway to clarify current behavior (are the anchors `<DVC_METRIC_X>` or `"<DVC_METRIC_X>"`)?

One more thought: it seems like only `<DVC_METRIC_DATA>` is ever anything other than a string, so maybe it makes sense to do a simple replace without quotes for everything other than that anchor?

**Comment by pared** [comment]
BTW @WilliamHarvey97 what kind of plot are you trying to implement? Maybe we could approach it in some other way.

**Comment by WilliamHarvey97** [comment]
I was implementing an actual v.s. predicted plot. I wanted to add MAPE, RMSE, R2 and other useful metrics to show at the top of the plot. We often share our results within my team and I found it useful to include these metrics at the top.

In the end, we chose to version png image. We wanted to use the color of each point to encode something else and in the current implementation of dvc-render, the color is reserved for version encoding. I prefer the side-to-side comparison of png.

**Comment by pared** [comment]
@WilliamHarvey97 Got it. Well, what you are trying to achieve should be the scope of iterative/dvc#7086. Would you mind sharing some example of your use case? I am preparing some backward incompatible changes for dvc 3.0 and knowing more use cases might help me define it better.

**Comment by pared** [comment]
@daniel-falk 
Good idea with the workaround. I will try to look into supporting this once iterative/dvc#7086 is done.
