### ISSUE TITLE
Using CSS in header breaks html templating

### ISSUE THREAD

**Issue by hv10** [iterative/dvc-render#58]
When using a custom html template for rendering plots I wanted to add some layout-directives by virtue of adding some CSS directives in the header of my template similar to this:
```html
<header>
  /* other stuff */
  <style>
    .grid {/*settings*/}
  </style>
</header>
```

This breaks the templating approach used by dvc_render, the offending function is `HTML.embed()` [line 86 @ref](https://github.com/iterative/dvc-render/blob/41d7900fce6b0a2f40d5643cd46898f10d25c49a/src/dvc_render/html.py#L86)

The usage of `.format` on the raw string of the template assumes that _everything_ in curly braces will be filled by the given kwargs, which seems unnecessarily restricted and should - if actually wanted - be documented either here or in the corresponding documentation of dvc.

The line in question could be replaced by an iteration over the valid kwargs where each of them is used for a replace operation.
Slightly less efficient, as there will be multiple passes over the content, but way more resilient to bad usage.

```python
# replace 
return self.template.format(**kwargs)
# with something along the lines of
for placeholder, value in kwargs.items():
    self.template = self.template.replace("{"+placeholder+"}", value)
return self.template
```

I would be willing to quickly write the specific changes and make a PR, but I am unsure about how to proceed with updating the corresponding unit-test, which uses the same `.format` and therefore fails on the same issue.
Should I just adjust the test to expect an explicit version of the string?

**Comment by daavoo** [comment]
Hi @hv10 . What if you escape the curly braces in your HTML template:

```diff
<header>
  /* other stuff */
  <style>
-    .grid {/*settings*/}
+    .grid {{/*settings*/}}
  </style>
</header>
```

**Comment by hv10** [comment]
That seems to work and produce the valid HTML output, if that is preferred over the solution of the PR I opened, I would like that to be reflected in the documentation of dvc if possible :)

Thank you for the help!

**Comment by daavoo** [comment]
> I would like that to be reflected in the documentation of dvc if possible

Agree. We need to improve the overall docs around custom templating as it is a little scarce right now
