### ISSUE TITLE
render: image: have option to diff images with a slider instead of side by side

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc-render#6]
See how tensorboard shows images over multiple steps for an example: https://stackoverflow.com/questions/43763858/change-images-slider-step-in-tensorboard.

It would be great to have an option to view like this instead of loading all image revisions side by side.

**Comment by daavoo** [comment]
@dberenbaum do you think we want to prioritize this or consider the image slider only a feature for the VSCode / Studio UIs

**Comment by dberenbaum** [comment]
I think we can close or at least not prioritize this. WDYT?

**Comment by daavoo** [comment]
Closing as not planned
